apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhp-flask-app
spec:
  replicas: 3  # Adjust the number of replicas as needed for your app's scalability
  selector:
    matchLabels:
      app: bhp-flask-app
  template:
    metadata:
      labels:
        app: bhp-flask-app
    spec:
      containers:
      - name: bhp-flask-app
        image: anirbanbhk/bhp-flask-app:latest  # Replace with your Docker image
        ports:
        - containerPort: 5000  # The port your Flask app is running on
