apiVersion: v1
kind: Service
metadata:
  name: bhp-flask-app-service
spec:
  selector:
    app: bhp-flask-app
  ports:
    - protocol: TCP
      port: 80  # Port to access the service from outside
      targetPort: 5000  # Port the container is listening on
  type: LoadBalancer  # Exposes the service to the internet (may vary depending on cloud provider)
